name: Manual Vehicle Info Autofill

on:
  workflow_dispatch: # Allows you to run it manually via a single click button

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install smartsheet-python-sdk requests

      - name: Run Vehicle Lookup
        run: python vehicle_lookup.py
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
          SMARTSHEET_ID: ${{ secrets.SMARTSHEET_ID }}
